# Generated by Django 2.1.7 on 2019-04-01 12:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='Производитель')),
                ('additionally', models.TextField(verbose_name='Дополнительно')),
            ],
        ),
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='Модель')),
                ('price', models.IntegerField(verbose_name='Стоимость')),
                ('os', models.CharField(max_length=32, verbose_name='Операционая система')),
                ('ram', models.IntegerField(verbose_name='Оперативная память')),
                ('ppi', models.IntegerField(verbose_name='Число пикселей на дюйм')),
                ('double_camera', models.BooleanField(verbose_name='Двойная камера')),
                ('processor', models.CharField(max_length=32, verbose_name='Процессор')),
                ('display', models.CharField(max_length=32, verbose_name='Разрешение экрана')),
                ('radio', models.BooleanField(verbose_name='FM-Радио')),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='phones.Manufacturer')),
            ],
        ),
    ]
