# Generated by Django 2.1.7 on 2019-04-18 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='station',
            options={'verbose_name': 'Остановка', 'verbose_name_plural': 'Остановки'},
        ),
    ]
