# Generated by Django 2.1.7 on 2019-04-15 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0003_auto_20190415_2202'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pathtocsv',
            options={'verbose_name': 'Путь к CSV', 'verbose_name_plural': 'Путь к CSV'},
        ),
        migrations.AlterModelOptions(
            name='tablefield',
            options={'ordering': ['index_number'], 'verbose_name': 'Поле таблицы', 'verbose_name_plural': 'Поля таблицы'},
        ),
    ]
